version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map frontend container's port 80 to host's port 8080
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: . # Set the build context to the root folder
      dockerfile: ./backend/Dockerfile # Specify the Dockerfile path relative to the root
    volumes:
      - ./backend/src:/app/src # Mount backend source code to /app inside the container
    ports:
      - "${PORT}:3000" # Map backend container's port 3000 to host's port 3000
    networks:
      - app-network
    env_file:
      - .env # Load environment variables from the .env file

networks:
  app-network:
    driver: bridge